function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function formatNumber(value){const n=Number(value);return Number.isFinite(n)?n.toFixed(6):"-";}
function prettifyFieldName(field){return String(field).replace(/^manual::/,"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function buildOptions(items,selectedValue,labelBuilder){return items.map((item)=>{const value=typeof item==="string"?item:item.id;const label=labelBuilder?labelBuilder(item):value;return `<option value="${escapeHtml(value)}" ${value===selectedValue?"selected":""}>${escapeHtml(label)}</option>`;}).join("");}
function parseJsonField(rawValue,label){const trimmed=rawValue.trim();if(!trimmed){return {};}try{const parsed=JSON.parse(trimmed);if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed)){return parsed;}throw new Error("Metadata must be a JSON object.");}catch{throw new Error(`${label} metadata is invalid JSON.`);}}
function renderMatrixTable(rows){if(!rows?.length){return `<div class="muted-note">No data available.</div>`;}const columns=Object.keys(rows[0]);return `<div class="table-wrap"><table><thead><tr>${columns.map((c)=>`<th>${escapeHtml(c)}</th>`).join("")}</tr></thead><tbody>${rows.map((row)=>`<tr>${columns.map((c)=>`<td>${escapeHtml(row[c])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function renderScoreBars(rows){if(!rows?.length){return `<div class="muted-note">No comparison score available.</div>`;}const maxValue=Math.max(...rows.map((row)=>Number(row.score||0)),0.00001);return `<div class="score-bars">${rows.map((row)=>{const width=(Number(row.score||0)/maxValue)*100;return `<div class="score-row"><strong>${escapeHtml(row.alternative_label||row.route_id||row.alternative_id)}</strong><div class="score-track"><div class="score-fill" style="width:${width}%"></div></div><span>${formatNumber(row.score)}</span></div>`;}).join("")}</div>`;}

export function createUI(){
const refs={
appShell:document.querySelector(".app-shell"),sidebar:document.querySelector("#sidebar"),navHome:document.querySelector("#nav-home"),navShortest:document.querySelector("#nav-shortest"),navHybrid:document.querySelector("#nav-hybrid"),clearWorkspaceBtn:document.querySelector("#clear-workspace-btn"),
datasetBadge:document.querySelector("#dataset-badge"),datasetStatus:document.querySelector("#dataset-status"),workspaceTitle:document.querySelector("#workspace-title"),mapModeNote:document.querySelector("#map-mode-note"),resultsTitle:document.querySelector("#results-title"),resultsBadge:document.querySelector("#results-badge"),flashMessage:document.querySelector("#flash-message"),resultsContent:document.querySelector("#results-content"),
workbookFile:document.querySelector("#workbook-file"),uploadExcelBtn:document.querySelector("#upload-excel-btn"),
nodeForm:document.querySelector("#node-form"),nodeFormMode:document.querySelector("#node-form-mode"),nodeEditId:document.querySelector("#node-edit-id"),nodeId:document.querySelector("#node-id"),nodeName:document.querySelector("#node-name"),nodeLatitude:document.querySelector("#node-latitude"),nodeLongitude:document.querySelector("#node-longitude"),nodeMetadata:document.querySelector("#node-metadata"),nodeActive:document.querySelector("#node-active"),clearNodeFormBtn:document.querySelector("#clear-node-form-btn"),nodesTableBody:document.querySelector("#nodes-table-body"),
edgeForm:document.querySelector("#edge-form"),edgeFormMode:document.querySelector("#edge-form-mode"),edgeEditIndex:document.querySelector("#edge-edit-index"),edgeSource:document.querySelector("#edge-source"),edgeTarget:document.querySelector("#edge-target"),edgeDistance:document.querySelector("#edge-distance"),edgeTime:document.querySelector("#edge-time"),edgeCost:document.querySelector("#edge-cost"),edgeRoadScore:document.querySelector("#edge-road-score"),edgeMetadata:document.querySelector("#edge-metadata"),clearEdgeFormBtn:document.querySelector("#clear-edge-form-btn"),edgesTableBody:document.querySelector("#edges-table-body"),
originSelect:document.querySelector("#origin-select"),destinationSelect:document.querySelector("#destination-select"),graphTypeSelect:document.querySelector("#graph-type-select"),metricSelect:document.querySelector("#metric-select"),activeNodesList:document.querySelector("#active-nodes-list"),buildGraphBtn:document.querySelector("#build-graph-btn"),runShortestBtn:document.querySelector("#run-shortest-btn"),customMetricPanel:document.querySelector("#custom-metric-panel"),customDistanceWeight:document.querySelector("#custom-distance-weight"),customTimeWeight:document.querySelector("#custom-time-weight"),customCostWeight:document.querySelector("#custom-cost-weight"),customRoadWeight:document.querySelector("#custom-road-weight"),
hybridStatus:document.querySelector("#hybrid-status"),hybridScenarioSelect:document.querySelector("#hybrid-scenario-select"),hybridOriginSelect:document.querySelector("#hybrid-origin-select"),hybridDestinationSelect:document.querySelector("#hybrid-destination-select"),hybridGraphTypeSelect:document.querySelector("#hybrid-graph-type-select"),hybridWeightMethodSelect:document.querySelector("#hybrid-weight-method-select"),hybridActiveNodesList:document.querySelector("#hybrid-active-nodes-list"),mcdmMethodSelect:document.querySelector("#mcdm-method-select"),hybridFieldSelect:document.querySelector("#hybrid-field-select"),hybridFieldKindSelect:document.querySelector("#hybrid-field-kind-select"),addImportedCriterionBtn:document.querySelector("#add-imported-criterion-btn"),hybridCriteriaEditor:document.querySelector("#hybrid-criteria-editor"),addHybridCriterionBtn:document.querySelector("#add-hybrid-criterion-btn"),runHybridBtn:document.querySelector("#run-hybrid-btn"),totalRawWeight:document.querySelector("#total-raw-weight"),totalNormalizedWeight:document.querySelector("#total-normalized-weight"),normalizeWeightsBtn:document.querySelector("#normalize-weights-btn"),manualValuesPanel:document.querySelector("#manual-values-panel"),manualValuesEditor:document.querySelector("#manual-values-editor"),
exportJsonBtn:document.querySelector("#export-json-btn"),exportCsvBtn:document.querySelector("#export-csv-btn"),exportGeoJsonBtn:document.querySelector("#export-geojson-btn")
};
let currentView="home";let hybridFieldOptions=[];let hybridEdgeAlternatives=[];
function setView(view){currentView=view;refs.navHome.classList.toggle("active",view==="home");refs.navShortest.classList.toggle("active",view==="shortest");refs.navHybrid.classList.toggle("active",view==="hybrid");refs.sidebar.classList.toggle("hidden",view==="home");refs.appShell.classList.toggle("sidebar-collapsed",view==="home");document.querySelectorAll(".shortest-only").forEach((el)=>el.classList.toggle("hidden",view!=="shortest"));document.querySelectorAll(".hybrid-only").forEach((el)=>el.classList.toggle("hidden",view!=="hybrid"));refs.workspaceTitle.textContent=view==="home"?"Map Workspace":view==="shortest"?"Shortest Path Workspace":"Hybrid Workspace";refs.resultsTitle.textContent=view==="home"?"Home":view==="shortest"?"Shortest Path":"Hybrid";}
function setFlash(message,tone="info"){refs.flashMessage.className=`flash-message ${tone}`;refs.flashMessage.textContent=message;}
function setDatasetBadge(text){refs.datasetBadge.textContent=text;}
function setResultsBadge(text){refs.resultsBadge.textContent=text;}
function setMapModeNote(text){refs.mapModeNote.textContent=text;}
function toggleShortestCustomMetric(){refs.customMetricPanel.classList.toggle("hidden",refs.metricSelect.value!=="custom");}
function toggleManualWeightArea(){const isManual=refs.hybridWeightMethodSelect.value==="manual";refs.normalizeWeightsBtn.classList.toggle("hidden",!isManual);refs.hybridCriteriaEditor.querySelectorAll(".criterion-weight").forEach((input)=>{input.disabled=!isManual;});}
function renderDatasetSummary(dataset,summary){const nodeCount=dataset?.nodes?.length||0;const edgeCount=dataset?.edges?.length||0;refs.datasetStatus.innerHTML=`<strong>${nodeCount}</strong> nodes and <strong>${edgeCount}</strong> edges loaded.<br />Active nodes: <strong>${escapeHtml(summary?.active_node_count??nodeCount)}</strong><br />Graph metric summary: <strong>${escapeHtml(summary?.metric||"-")}</strong>${summary?.warnings?.length?`<div class="muted-note">${escapeHtml(summary.warnings.join(" "))}</div>`:`<div class="muted-note">Belum ada warning pada dataset aktif.</div>`}`;refs.hybridStatus.textContent=nodeCount?"Hybrid analysis siap memakai dataset yang sudah diimpor.":"Impor dataset terlebih dahulu pada menu Shortest Path.";setDatasetBadge(nodeCount?"Loaded":"Empty");}
function renderNodeTable(nodes){refs.nodesTableBody.innerHTML=nodes.map((node)=>`<tr><td><strong>${escapeHtml(node.id)}</strong><br /><span class="muted-note">${escapeHtml(node.name)}</span></td><td>${escapeHtml(node.active?"Active":"Inactive")}</td><td><button type="button" class="tiny-button" data-node-action="edit" data-node-id="${escapeHtml(node.id)}">Edit</button><button type="button" class="tiny-button danger" data-node-action="delete" data-node-id="${escapeHtml(node.id)}">Delete</button></td></tr>`).join("");}
function renderEdgeTable(edges){refs.edgesTableBody.innerHTML=edges.map((edge,index)=>`<tr><td><strong>${escapeHtml(edge.metadata?.__edge_label||`${edge.source} -> ${edge.target}`)}</strong></td><td>${edge.metadata?._missing_distance?"Input manual":formatNumber(edge.distance)}</td><td><button type="button" class="tiny-button" data-edge-action="edit" data-edge-index="${index}">Edit</button><button type="button" class="tiny-button danger" data-edge-action="delete" data-edge-index="${index}">Delete</button></td></tr>`).join("");}
function renderNodeSelectors(nodes,options={}){const so=options.shortestOrigin||nodes[0]?.id||"";const sd=options.shortestDestination||nodes.at(-1)?.id||"";const ho=options.hybridOrigin||so;const hd=options.hybridDestination||sd;const markup=buildOptions(nodes,null,(node)=>`${node.id} - ${node.name}`);refs.originSelect.innerHTML=markup;refs.destinationSelect.innerHTML=markup;refs.hybridOriginSelect.innerHTML=markup;refs.hybridDestinationSelect.innerHTML=markup;refs.originSelect.value=so;refs.destinationSelect.value=sd;refs.hybridOriginSelect.value=ho;refs.hybridDestinationSelect.value=hd;}
function renderEdgeNodeOptions(nodes,selectedSource="",selectedTarget=""){const markup=buildOptions(nodes,null,(node)=>`${node.id} - ${node.name}`);refs.edgeSource.innerHTML=markup;refs.edgeTarget.innerHTML=markup;if(selectedSource){refs.edgeSource.value=selectedSource;}if(selectedTarget){refs.edgeTarget.value=selectedTarget;}}
function renderActiveNodes(nodes,selectedIds=[],target="shortest"){const container=target==="hybrid"?refs.hybridActiveNodesList:refs.activeNodesList;const selected=new Set(selectedIds.length?selectedIds:nodes.filter((node)=>node.active).map((node)=>node.id));container.innerHTML=nodes.map((node)=>`<label class="checklist-item"><input type="checkbox" value="${escapeHtml(node.id)}" ${selected.has(node.id)?"checked":""} /><span>${escapeHtml(node.id)} - ${escapeHtml(node.name)}</span></label>`).join("");}
function resetNodeForm(){refs.nodeForm.reset();refs.nodeEditId.value="";refs.nodeMetadata.value="{}";refs.nodeActive.checked=true;refs.nodeFormMode.textContent="Add";refs.nodeId.disabled=false;}
function fillNodeForm(node){refs.nodeEditId.value=node.id;refs.nodeId.value=node.id;refs.nodeName.value=node.name;refs.nodeLatitude.value=node.latitude;refs.nodeLongitude.value=node.longitude;refs.nodeMetadata.value=JSON.stringify(node.metadata||{},null,2);refs.nodeActive.checked=Boolean(node.active);refs.nodeFormMode.textContent="Edit";refs.nodeId.disabled=true;}
function resetEdgeForm(){refs.edgeForm.reset();refs.edgeEditIndex.value="";refs.edgeMetadata.value="{}";refs.edgeCost.value=0;refs.edgeRoadScore.value=3;refs.edgeFormMode.textContent="Add";}
function fillEdgeForm(edge,index){refs.edgeEditIndex.value=index;refs.edgeSource.value=edge.source;refs.edgeTarget.value=edge.target;refs.edgeDistance.value=edge.metadata?._missing_distance?"":edge.distance;refs.edgeTime.value=edge.time;refs.edgeCost.value=edge.cost;refs.edgeRoadScore.value=edge.road_condition_score;refs.edgeMetadata.value=JSON.stringify(edge.metadata||{},null,2);refs.edgeFormMode.textContent="Edit";}
function readNodeForm(){return{id:refs.nodeId.value.trim(),name:refs.nodeName.value.trim(),latitude:Number(refs.nodeLatitude.value),longitude:Number(refs.nodeLongitude.value),metadata:parseJsonField(refs.nodeMetadata.value,"Node"),active:refs.nodeActive.checked};}
function readEdgeForm(){return{source:refs.edgeSource.value,target:refs.edgeTarget.value,distance:Number(refs.edgeDistance.value),time:Number(refs.edgeTime.value),cost:Number(refs.edgeCost.value),road_condition_score:Number(refs.edgeRoadScore.value),metadata:parseJsonField(refs.edgeMetadata.value,"Edge")};}
function readSelectedNodes(target="shortest"){const container=target==="hybrid"?refs.hybridActiveNodesList:refs.activeNodesList;return [...container.querySelectorAll("input[type='checkbox']:checked")].map((box)=>box.value);}
function readShortestConfig(){return{origin_id:refs.originSelect.value,destination_id:refs.destinationSelect.value,graph_type:refs.graphTypeSelect.value,metric:refs.metricSelect.value,active_node_ids:readSelectedNodes("shortest"),custom_metric_weights:{distance:Number(refs.customDistanceWeight.value),time:Number(refs.customTimeWeight.value),cost:Number(refs.customCostWeight.value),road_condition:Number(refs.customRoadWeight.value)}};}
function setHybridFieldOptions(fieldOptions){hybridFieldOptions=fieldOptions;refs.hybridFieldSelect.innerHTML=buildOptions(fieldOptions,fieldOptions[0]?.id||"",(item)=>item.label);}
function setHybridEdgeAlternatives(alternatives){hybridEdgeAlternatives=alternatives||[];}
function updateWeightTotals(normalizedWeights=null){const rawWeights=[...refs.hybridCriteriaEditor.querySelectorAll(".criterion-weight")].map((input)=>Number(input.value||0));const totalRaw=rawWeights.reduce((sum,item)=>sum+item,0);refs.totalRawWeight.value=formatNumber(totalRaw);refs.totalNormalizedWeight.value=formatNumber(normalizedWeights?normalizedWeights.reduce((sum,item)=>sum+item,0):(totalRaw>0?1:0));}
function renderManualValuesEditor(){const existingValues={};refs.manualValuesEditor.querySelectorAll("[data-manual-criterion-id]").forEach((input)=>{existingValues[`${input.dataset.manualCriterionId}::${input.dataset.alternativeId}`]=input.value;});const manualCriteria=[...refs.hybridCriteriaEditor.querySelectorAll(".criterion-row")].filter((row)=>row.dataset.field.startsWith("manual::"));refs.manualValuesPanel.classList.toggle("hidden",manualCriteria.length===0);if(!manualCriteria.length){refs.manualValuesEditor.innerHTML="";return;}refs.manualValuesEditor.innerHTML=manualCriteria.map((row)=>{const criterionId=row.dataset.criterionId;const criterionLabel=row.querySelector(".criterion-label").value.trim()||"Manual Criterion";return `<div class="result-card"><h3>${escapeHtml(criterionLabel)}</h3><div class="table-wrap"><table><thead><tr><th>Alternative</th><th>Value</th></tr></thead><tbody>${hybridEdgeAlternatives.map((alternative)=>{const key=`${criterionId}::${alternative.alternative_id}`;return `<tr><td>${escapeHtml(alternative.alternative_label)}</td><td><input type="number" step="any" data-manual-criterion-id="${escapeHtml(criterionId)}" data-alternative-id="${escapeHtml(alternative.alternative_id)}" value="${escapeHtml(existingValues[key]??"")}" /></td></tr>`;}).join("")}</tbody></table></div></div>`;}).join("");}
function renderHybridCriteria(criteria=[]){refs.hybridCriteriaEditor.innerHTML=`<div class="criteria-header"><span>Label</span><span>Field</span><span>Type</span><span>Raw Weight</span><span>Action</span></div>${criteria.map((criterion)=>`<div class="criterion-row" data-criterion-id="${escapeHtml(criterion.criterion_id)}" data-field="${escapeHtml(criterion.field)}"><input type="text" class="criterion-label" value="${escapeHtml(criterion.label)}" ${criterion.is_manual?"":"readonly"} /><input type="text" class="criterion-field-label" value="${escapeHtml(criterion.field_label)}" readonly /><select class="criterion-kind"><option value="cost" ${criterion.kind==="cost"?"selected":""}>Cost</option><option value="benefit" ${criterion.kind==="benefit"?"selected":""}>Benefit</option></select><input type="number" class="criterion-weight" min="0" step="any" value="${criterion.weight??0}" /><button type="button" class="tiny-button danger remove-criterion-btn">Remove</button></div>`).join("")}`;updateWeightTotals();renderManualValuesEditor();toggleManualWeightArea();}
function addImportedCriterion(fieldId,kind){const option=hybridFieldOptions.find((item)=>item.id===fieldId);if(!option){return;}const criterionId=`imported::${fieldId}`;if([...refs.hybridCriteriaEditor.querySelectorAll(".criterion-row")].some((row)=>row.dataset.criterionId===criterionId)){return;}refs.hybridCriteriaEditor.insertAdjacentHTML("beforeend",`<div class="criterion-row" data-criterion-id="${escapeHtml(criterionId)}" data-field="${escapeHtml(fieldId)}"><input type="text" class="criterion-label" value="${escapeHtml(option.label)}" readonly /><input type="text" class="criterion-field-label" value="${escapeHtml(option.label)}" readonly /><select class="criterion-kind"><option value="cost" ${kind==="cost"?"selected":""}>Cost</option><option value="benefit" ${kind==="benefit"?"selected":""}>Benefit</option></select><input type="number" class="criterion-weight" min="0" step="any" value="1" /><button type="button" class="tiny-button danger remove-criterion-btn">Remove</button></div>`);updateWeightTotals();toggleManualWeightArea();}
function addManualCriterion(){const criterionId=`manual::criterion_${Date.now()}`;refs.hybridCriteriaEditor.insertAdjacentHTML("beforeend",`<div class="criterion-row" data-criterion-id="${escapeHtml(criterionId)}" data-field="${escapeHtml(criterionId)}"><input type="text" class="criterion-label" value="Manual Criterion" /><input type="text" class="criterion-field-label" value="Input manual" readonly /><select class="criterion-kind"><option value="cost">Cost</option><option value="benefit">Benefit</option></select><input type="number" class="criterion-weight" min="0" step="any" value="1" /><button type="button" class="tiny-button danger remove-criterion-btn">Remove</button></div>`);updateWeightTotals();renderManualValuesEditor();toggleManualWeightArea();}
function normalizeDisplayedWeights(){const inputs=[...refs.hybridCriteriaEditor.querySelectorAll(".criterion-weight")];const values=inputs.map((input)=>Number(input.value||0));const total=values.reduce((sum,item)=>sum+item,0);if(total<=0){throw new Error("Manual weights must have a positive total.");}const normalized=values.map((value)=>value/total);inputs.forEach((input,index)=>{input.value=normalized[index].toFixed(6);});updateWeightTotals(normalized);}
function readHybridConfig(){const criteria=[...refs.hybridCriteriaEditor.querySelectorAll(".criterion-row")].map((row)=>{const criterionId=row.dataset.criterionId;const field=row.dataset.field;const manualValues={};if(field.startsWith("manual::")){refs.manualValuesEditor.querySelectorAll(`[data-manual-criterion-id="${CSS.escape(criterionId)}"]`).forEach((input)=>{if(String(input.value).trim()!==""){manualValues[input.dataset.alternativeId]=Number(input.value);}});}return{criterion_id:criterionId,field,label:row.querySelector(".criterion-label").value.trim(),kind:row.querySelector(".criterion-kind").value,weight:Number(row.querySelector(".criterion-weight").value||0),manual_values:manualValues};});return{origin_id:refs.hybridOriginSelect.value,destination_id:refs.hybridDestinationSelect.value,graph_type:refs.hybridGraphTypeSelect.value,method:refs.mcdmMethodSelect.value,active_node_ids:readSelectedNodes("hybrid"),weight_method:refs.hybridWeightMethodSelect.value,scenario:refs.hybridScenarioSelect.value,criteria};}
function renderHome(){refs.resultsContent.innerHTML=`<div class="result-card"><h3>Selamat Datang</h3><p class="muted-note">Peta dibuka di Kota Medan sebagai tampilan awal. Tidak ada perhitungan default pada startup.</p><div class="metrics-grid"><div class="metric-pill"><span>Home</span><strong>Orientasi workspace dan petunjuk singkat.</strong></div><div class="metric-pill"><span>Shortest Path</span><strong>Jalankan Dijkstra pada graph yang Anda impor.</strong></div><div class="metric-pill"><span>Hybrid</span><strong>Gunakan shortest path + MCDM dari data edge impor.</strong></div><div class="metric-pill"><span>Kota Awal</span><strong>Map workspace default berada di Medan.</strong></div></div></div>`;setResultsBadge("Ready");}
function renderEmptyAnalysis(mode){refs.resultsContent.innerHTML=`<div class="placeholder-block">${mode==="shortest"?"Belum ada hasil shortest path. Impor data, pilih origin dan destination, lalu jalankan Dijkstra.":"Belum ada hasil hybrid. Pilih skenario, susun kriteria dari datafix, lalu jalankan hybrid analysis."}</div>`;setResultsBadge("Empty");}
function renderShortestResults({summary,primaryRoute}){if(!primaryRoute){renderEmptyAnalysis("shortest");return;}refs.resultsContent.innerHTML=`<div class="result-card"><h3>Shortest Path Result</h3><div class="metrics-grid"><div class="metric-pill"><span>Distance</span><strong>${formatNumber(primaryRoute.total_distance)}</strong></div><div class="metric-pill"><span>Time</span><strong>${formatNumber(primaryRoute.total_time)}</strong></div><div class="metric-pill"><span>Cost</span><strong>${formatNumber(primaryRoute.total_cost)}</strong></div><div class="metric-pill"><span>Road Condition</span><strong>${formatNumber(primaryRoute.average_road_condition)}</strong></div><div class="metric-pill"><span>Hops</span><strong>${escapeHtml(primaryRoute.hops)}</strong></div><div class="metric-pill"><span>Optimized Weight</span><strong>${formatNumber(primaryRoute.optimized_weight)}</strong></div></div><div class="route-sequence">${primaryRoute.path_names.map((name,index)=>`<span class="route-chip">${index+1}. ${escapeHtml(name)}</span>`).join("")}</div></div><div class="result-card"><h3>Graph Summary</h3>${renderMatrixTable([summary])}</div>`;setResultsBadge("Completed");}
function renderHybridResults(result){if(!result?.route_result){renderEmptyAnalysis("hybrid");return;}const route=result.route_result;refs.resultsContent.innerHTML=`<div class="result-card"><h3>Hybrid Route Result</h3><p class="muted-note">${escapeHtml(result.explanation)}</p><div class="metrics-grid"><div class="metric-pill"><span>Scenario</span><strong>${escapeHtml(result.scenario)}</strong></div><div class="metric-pill"><span>Method</span><strong>${escapeHtml(result.method.toUpperCase())}</strong></div><div class="metric-pill"><span>Weight Method</span><strong>${escapeHtml(result.weight_method)}</strong></div><div class="metric-pill"><span>Optimized Weight</span><strong>${formatNumber(route.optimized_weight)}</strong></div><div class="metric-pill"><span>Distance</span><strong>${formatNumber(route.total_distance)}</strong></div><div class="metric-pill"><span>Time</span><strong>${formatNumber(route.total_time)}</strong></div></div><div class="route-sequence">${route.path_names.map((name,index)=>`<span class="route-chip">${index+1}. ${escapeHtml(name)}</span>`).join("")}</div></div><div class="result-card"><h3>Weight Table</h3>${renderMatrixTable(result.weights_table)}</div>${result.decision_matrix?.length?`<div class="result-card"><h3>Global Edge Decision Matrix</h3>${renderMatrixTable(result.decision_matrix)}</div><div class="result-card"><h3>Global Edge Ranking</h3>${renderMatrixTable(result.ranking)}${renderScoreBars(result.ranking)}</div>`:""}${result.local_steps?.length?`<div class="result-card"><h3>Local MCDM Steps</h3>${renderMatrixTable(result.local_steps.map((step,index)=>({step:index+1,from_node:step.from_node,to_node:step.to_node,selected_alternative:step.selected_alternative_label,selected_score:formatNumber(step.selected_score)})))}</div>`:""}`;setResultsBadge("Completed");}
function downloadFile(filename,content,mimeType){const blob=new Blob([content],{type:mimeType});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();document.body.removeChild(link);URL.revokeObjectURL(url);}
setView("home");renderHome();toggleShortestCustomMetric();toggleManualWeightArea();resetNodeForm();resetEdgeForm();renderHybridCriteria([]);
return{refs,get currentView(){return currentView;},setView,setFlash,setDatasetBadge,setResultsBadge,setMapModeNote,toggleShortestCustomMetric,toggleManualWeightArea,renderDatasetSummary,renderNodeTable,renderEdgeTable,renderNodeSelectors,renderEdgeNodeOptions,renderActiveNodes,resetNodeForm,fillNodeForm,resetEdgeForm,fillEdgeForm,readNodeForm,readEdgeForm,readShortestConfig,readHybridConfig,setHybridFieldOptions,setHybridEdgeAlternatives,renderHybridCriteria,addImportedCriterion,addManualCriterion,renderManualValuesEditor,updateWeightTotals,normalizeDisplayedWeights,renderHome,renderEmptyAnalysis,renderShortestResults,renderHybridResults,downloadFile,prettifyFieldName};}
